
drop table TRAVEL;
drop table TRANSACTION;
drop table RUN;
drop table NOTE;
drop table CATEGORY;

drop table PERSON_PERMISSION;
drop table PERSON;
drop table PERMISSION;



CREATE TABLE PERSON (
	ID VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL UNIQUE,
	FIRST_NAME VARCHAR(255) NOT NULL,
	LAST_NAME VARCHAR(255) NOT NULL,
	PASSWORD VARCHAR(255) NOT NULL,
	ROLE VARCHAR(16) check(ROLE in ('TRAVEL_PLANNER', 'EXPENSE_TRACKER', 'RUNS_TRACKER', 'NOTES_MANAGER', 'ADMIN')),
	STATUS VARCHAR(10) check(STATUS in ('ACTIVE', 'SUSPENDED')),
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (ID)
);

CREATE TABLE PERMISSION (
	ID  integer NOT NULL,
	NAME VARCHAR(20) NOT NULL UNIQUE,
	PRIMARY KEY (ID)
);

CREATE TABLE PERSON_PERMISSION (
	PERMISSION_ID  integer NOT NULL,
	PERSON_ID VARCHAR(255) NOT NULL,
	PRIMARY KEY (PERSON_ID, PERMISSION_ID),
	CONSTRAINT FK_PERSON_ID FOREIGN KEY (PERSON_ID) references PERSON(ID) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT FK_PERMISSION_ID FOREIGN KEY (PERMISSION_ID) references PERMISSION(ID) ON UPDATE CASCADE ON DELETE CASCADE
);


CREATE TABLE CATEGORY (
	ID VARCHAR(255) NOT NULL,
	NAME VARCHAR(255) NOT NULL UNIQUE,
	CREATED_BY VARCHAR(255) NOT NULL,

	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (ID),
	CONSTRAINT FK_CATEGORY_CREATED_BY FOREIGN KEY (CREATED_BY) references PERSON(ID) ON UPDATE CASCADE ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE TRAVEL (
	ID VARCHAR(255) NOT NULL,
	DESTINATION VARCHAR(255) NOT NULL,
	START_DATE TIMESTAMP NOT NULL,
	END_DATE TIMESTAMP NOT NULL,
	COMMENT VARCHAR(255),
	CREATED_BY VARCHAR(255) NOT NULL,
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (ID),
	CONSTRAINT FK_TRAVEL_CREATED_BY FOREIGN KEY (CREATED_BY) references PERSON(ID) ON UPDATE CASCADE ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE TRANSACTION (
	ID VARCHAR(255) NOT NULL,
	SUBJECT VARCHAR(255) NOT NULL,
	CATEGORY_ID VARCHAR(255) NOT NULL,

	AMOUNT FLOAT NOT NULL,
	DATE TIMESTAMP NOT NULL,
	TYPE VARCHAR(10) check(TYPE in ('WITHDRAWAL','DEPOSIT')),
  CREATED_BY VARCHAR(255) NOT NULL,

	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (ID),
	CONSTRAINT FK_TRANSACTION_CATEGORY_ID FOREIGN KEY (CATEGORY_ID) references CATEGORY(ID) ON UPDATE CASCADE ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT FK_TRANSACTION_CREATED_BY FOREIGN KEY (CREATED_BY) references PERSON(ID) ON UPDATE CASCADE ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE RUN (
	ID VARCHAR(255) NOT NULL,
	DATE TIMESTAMP NOT NULL,
	TOTAL_TIME TIMESTAMP NOT NULL,
	DISTANCE FLOAT,
	VELOCITY FLOAT,
	CREATED_BY VARCHAR(255) NOT NULL,
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (ID),
	CONSTRAINT FK_RUN_CREATED_BY FOREIGN KEY (CREATED_BY) references PERSON(ID) ON UPDATE CASCADE ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE NOTE (
	ID VARCHAR(255) NOT NULL,
	TITLE VARCHAR(255) NOT NULL,
	DESCRIPTION VARCHAR(255) NOT NULL,
	CATEGORY_ID VARCHAR(255) NOT NULL,
	CREATED_BY VARCHAR(255) NOT NULL,
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (ID),
	CONSTRAINT FK_NOTE_CATEGORY_ID FOREIGN KEY (CATEGORY_ID) references CATEGORY(ID) ON UPDATE CASCADE ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT FK_NOTE_CREATED_BY FOREIGN KEY (CREATED_BY) references PERSON(ID) ON UPDATE CASCADE ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);


INSERT INTO PERMISSION (ID, NAME) VALUES(1, 'CREATE');
INSERT INTO PERMISSION (ID, NAME) VALUES(2, 'READ');
INSERT INTO PERMISSION (ID, NAME) VALUES(3, 'UPDATE');
INSERT INTO PERMISSION (ID, NAME) VALUES(4, 'DELETE');
INSERT INTO PERMISSION (ID, NAME) VALUES(5, 'EXPORT');
INSERT INTO PERMISSION (ID, NAME) VALUES(6, 'READ_ALL');


INSERT INTO public.person(
            id, email, first_name, last_name, password, role, status, created_at,
            updated_at)
    VALUES ('79410A00-81EB-4B2A-B8C9-EAF368986FDB', 'admin@admin.com', 'admin', 'admin', '$s0$e0801$fkSZPnMiQm0R/KmuipflvQ==$J8t7f+fw2fIovYwW4cs7evK574c4IuBdCM6BUUtYfEU=', 'ADMIN', 'ACTIVE', current_timestamp, current_timestamp);

INSERT INTO public.person_permission(
            permission_id, person_id)
    VALUES (1, '79410A00-81EB-4B2A-B8C9-EAF368986FDB');

INSERT INTO public.person_permission(
            permission_id, person_id)
    VALUES (2, '79410A00-81EB-4B2A-B8C9-EAF368986FDB');

INSERT INTO public.person_permission(
            permission_id, person_id)
    VALUES (3, '79410A00-81EB-4B2A-B8C9-EAF368986FDB');

INSERT INTO public.person_permission(
            permission_id, person_id)
    VALUES (4, '79410A00-81EB-4B2A-B8C9-EAF368986FDB');

INSERT INTO public.person_permission(
            permission_id, person_id)
    VALUES (5, '79410A00-81EB-4B2A-B8C9-EAF368986FDB');

INSERT INTO public.person_permission(
            permission_id, person_id)
    VALUES (6, '79410A00-81EB-4B2A-B8C9-EAF368986FDB');